SELECT
CAST(id AS INT) as id,
vin,	
zip,	
make,	
year,	
model,	
county,	
office,	
status,	
on_hold,	
partner,
CAST(user_id as INT) as user_id,	
archived,	
initials,	
client_id,	
last_name,	
sales_tax,	
CAST(created_at as TIMESTAMP) as created_at,
first_name,	
CAST(updated_at as TIMESTAMP) as updated_at,
archived_at,	
submitted_on,	
CAST(contractor_id as INT) as contractor_id,
invoice_status,	
on_hold_reason,	
taxable_amount,	
transaction_id,
rejection_reason,	
unread_psb_messages,	
_airbyte_ab_id,	
ingested_at,
_airbyte_normalized_at,	
_airbyte_t_ingest_sales_tax_hashid,
FROM {{ source('ds_airbyte', 't_ingest_sales_tax') }}