version: 2

models:
  - name: v_transform_action
    unique_key: id
    columns:
      - name: id
        tests:
          - unique
          - not_null
          - row_count:
              above: 100
  - name: v_transform_permit
    columns:
      - name: id
        tests:
          - unique
          - not_null
          - row_count:
              above: 171
  - name: v_transform_registration
    columns:
      - name: id
        tests:
          - unique
          - not_null
  - name: v_transform_invoice
    columns: 
      - name: id
        tests:
          - unique
          - not_null
          - row_count:
              above: 450
      - name: status
        tests:
          - not_null
          - accepted_values:
              values: ['Sent', 'Paid']
  - name: t_dev_report_sto_invoice_approved_mvr
    columns:
      - name: invoice_id
        tests:
          - not_null
          - row_count:
              above: 26
      - name: sales_tax_id
        tests:
          - not_null
      - name: invoice_status
        tests:
          - not_null
          - accepted_values:
              values: ['Sent', 'Paid']
  - name: t_dev_report_action
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 81473
  - name: v_transform_county
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 61
  - name: v_transform_boat_information
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 30
  - name: t_dev_report_action_user
    columns:
      - name: action_id
        tests:
          - not_null
          - row_count:
              above: 81487
      - name: user_id
        tests:
          - not_null
  - name: t_dev_report_daily_transaction_status_totals
    columns:
      - name: status
        tests:
          - not_null
          - row_count:
              above: 21
  - name: t_dev_report_document
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 5119
  - name: v_transform_internal_note
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 37
  - name: v_transform_internal_note_type
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 4
  - name: t_dev_report_id_upgrade_phone_preference
    columns:
      - name: transaction_id
        tests:
          - not_null
          - row_count:
              above: 5
  - name: t_dev_report_id_upgrade_visit_outcomes
    columns:
      - name: transaction_id
        tests:
          - not_null
  - name: t_dev_report_invoice
    columns:
      - name: id
        tests:
          - not_null
          - unique
  - name: t_dev_report_invoice_cash
    columns:
      - name: amount
        tests:
          - not_null
      - name: invoice_status
        tests:
          - not_null
          - accepted_values:
              values: ['Sent', 'Paid']
  - name: t_dev_report_invoice_registration
    columns:
      - name: invoice_id
        tests:
          - not_null
      - name: invoice_status
        tests:
          - not_null
          - accepted_values:
              values: ['Sent', 'Paid']
  - name: t_dev_report_invoice_registration_user
    columns:
      - name: invoice_id
        tests:
          - not_null
          - row_count:
              above: 364
      - name: invoice_status
        tests:
          - not_null
          - accepted_values:
              values: ['Sent', 'Paid']
  - name: t_dev_report_invoice_registration_user_fulfilled_action
    columns:
      - name: invoice_id
        tests:
          - not_null
      - name: invoice_status
        tests:
          - not_null
          - accepted_values:
              values: ['Sent', 'Paid']
  - name: t_dev_report_invoice_sales_tax_user_fulfilled_action
    columns:
      - name: invoice_id
        tests:
          - not_null
      - name: invoice_status
        tests:
          - not_null
          - accepted_values:
              values: ['Sent', 'Paid']
  - name: t_dev_report_license_amendment
    columns:
      - name: id
        tests:
          - not_null
          - unique
  - name: t_dev_report_license_reciprocity
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 139
  - name: t_dev_report_message
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 1776
  - name: t_dev_report_most_performant_invoices
    columns:
      - name: invoice_id
        tests:
          - not_null
          - row_count:
              above: 79
  - name: t_dev_report_mvr_or_op_sessions_v_5_2
    columns:
      - name: user_id
        tests:
          - not_null
          - row_count:
              above: 471
  - name: t_dev_report_mvr_sessions
    columns:
      - name: first_name
        tests:
          - row_count:
              above: 13
  - name: t_dev_report_mvr_sessions_office
    columns:
      - name: user_office
  - name: t_dev_report_non_driver_id
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 125
  - name: t_dev_report_op_or_info_req_avg
    columns:
      - name: permit_approved_date
  - name: t_dev_report_op_status_avg_time_days
    columns:
      - name: approved_date
        tests:
          - row_count:
              above: 23
  - name: t_dev_report_original_title_info_req_reasons
    columns:
      - name: content
        tests:
          - row_count:
              above: 1775
  - name: t_dev_report_permit
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 171
  - name: t_dev_report_permit_actions
    columns:
      - name: action_id
        tests:
          - not_null
          - row_count:
              above: 5142
  - name: t_dev_report_blocked_transactions
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 5
  - name: t_dev_report_permit_by_ip_address
    columns:
      - name: transaction_id
        tests:
          - not_null
  - name: t_dev_report_permit_county_view
    columns:
      - name: transaction_id
        tests:
          - not_null
          - row_count:
              above: 4
  - name: t_dev_report_event_log_with_count
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 494
  - name: t_dev_report_permit_event_timeline
    columns:
      - name: transaction_id
        tests:
          - not_null
          - row_count:
              above: 621
  - name: t_dev_report_permit_ip_address
    columns:
      - name: id
        tests:
          - not_null
          - row_count:
              above: 115
  - name: t_dev_report_permit_ip_address_event_count_pivot
    columns:
      - name: ip_address
  - name: t_dev_report_permit_ip_test_status_summary
    columns:
      - name: ip_address
        tests:
          - row_count:
              above: 26
  - name: t_dev_report_permit_test_block_event_log
    columns:
      - name: ip_address
        tests:
          - row_count:
              above: 126
  - name: t_dev_report_permits_actioned_on
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 154
  - name: t_dev_report_purge_report_stats
    columns:
      - name: transaction_type
        tests:
          - not_null
          - row_count:
              above: 167
  - name: t_dev_report_registration
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 406
  - name: t_dev_report_registration_actions
    columns:
      - name: action_id
        tests:
          - not_null
          - row_count:
              above: 45199
  - name: t_dev_report_sales_tax
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 201
  - name: t_dev_report_temporary_inspection_activation_time
    columns:
      - name: d
        tests:
          - not_null
          - row_count:
              above: 9
  - name: t_dev_report_transaction_view_report
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 2909
  - name: t_dev_report_unique_user_transaction_count
    columns:
      - name: transaction_id
        tests:
          - not_null
          - row_count:
              above: 171
  - name: t_dev_report_unsuccessful_visit_reason
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 5
  - name: t_dev_report_user
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - row_count:
              above: 29
sources:
  - name: ds_airbyte
    tables:
      - name: t_ingest_action
        columns:
          - name: id
        freshness:
          warn_after:
            count: 3
            period: day
          error_after:
            count: 7
            period: day
        loaded_at_field: _airbyte_emitted_at
      - name: t_ingest_document
      - name: t_ingest_invoice
      - name: t_ingest_sales_tax
      - name: t_ingest_user
      - name: t_ingest_registration
      - name: t_ingest_registration_address
      - name: t_ingest_message
      - name: t_ingest_permit
      - name: t_ingest_permit_event_log
      - name: t_ingest_purge_report
      - name: t_ingest_internal_note
      - name: t_ingest_unsuccessful_visit_reason
      - name: t_ingest_boat_information
      - name: t_ingest_non_driver_id
      - name: t_ingest_county
      - name: t_ingest_internal_note_type
      - name: t_ingest_license_reciprocity
      - name: t_ingest_permit_test_block_event_log
      - name: t_ingest_license_amendment
      - name: t_ingest_id_upgrade
