version: 2

models:
  - name: v_transform_action
    columns:
      - name: id
        tests:
          - unique
          - not_null
  - name: sq_report_sto_invoice_approved_mvr
    columns:
      - name: invoice_id
        tests:
          - not_null
      - name: sales_tax_id
        tests:
          - not_null
