SELECT
CAST(id AS INT) as id,
vin,	
zip,	
make,	
year,	
model,	
county,	
office,	
status,	
on_hold,	
partner,
CAST(user_id as INT) as user_id,	
archived,	
initials,	
client_id,	
last_name,	
sales_tax,	
created_at,	
first_name,	
updated_at,	
archived_at,	
submitted_on,	
CAST(contractor_id as INT) as contractor_id,
invoice_status,	
on_hold_reason,	
taxable_amount,	
transaction_id,	
rejection_reason,	
unread_psb_messages,	
_airbyte_ab_id,	
_airbyte_emitted_at as ingested_at,	
_airbyte_normalized_at,	
_airbyte_sales_tax_hashid,	
FROM `playground-m-sterling`.airbyte.sales_tax