select
    day,
    user_office,
    count(user_id) as num_mvrs,
    sum(worked_mins) as total_work_time,
    floor(sum(worked_mins)/count(user_id)) as avg_per_mvr,
    sum(total_per_day)-sum(original_registration_assign_unassign)-sum(original_permit_assign_unassign)+sum(original_permit_assign_unassign) +(sum(original_registration_assign_unassign)/2) as total_actions,
    sum(original_permit_assign_unassign)+sum(original_registration_assign_unassign)/2 as total_transaction_views,
    sum(original_permit_info_requested) as op_info_requested,
    sum(original_permit_approved) as op_approvals,
    sum(original_permit_approved)+sum(original_permit_info_requested) as op_prod_actions,
    sum(original_permit_document_review) as op_document_reviews,
    sum(original_registration_info_requested) as or_info_requested,
    sum(original_registration_invoiced) as or_invoice_sent,
    sum(original_registration_fulfilled) as or_fulfilled,
    sum(original_registration_rejected) as or_rejected,
    sum(original_registration_info_requested)+sum(original_registration_invoiced)+sum(original_registration_fulfilled)+ sum(original_registration_rejected) as or_productive_actions,
    sum(original_registration_document_review) as or_document_reviews,
from {{ ref('v_transform_mvr_or_op_sessions_v_5_2')}} group by day, user_office
