dmv:
  outputs:
    dev:
      dataset: ds_transform
      fixed_retries: 1
      keyfile: /home/mathieson/code/nuvalence/playground-m-sterling-dbt.json
      location: US
      method: service-account
      priority: interactive
      project: playground-m-sterling
      threads: 1
      timeout_seconds: 300
      type: bigquery
  target: dev
